#!/usr/bin/with-contenv bash

exec /traefik --api.insecure=true --providers.docker=true --providers.docker.exposedbydefault=false --entrypoints.web.address=:80 --entrypoints.websecure.address=:443 --certificatesresolvers.myresolver.acme.dnschallenge=true --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare --certificatesresolvers.myresolver.acme.email=xxxt1213@gmail.com --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
